name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: uzair-haq
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_people: yes
          plugin_traffic: yes


